-- Create profiles table to extend auth.users
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  subscription_status text default 'free',
  stripe_customer_id text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on Row Level Security
alter table profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create drops table
create table drops (
  id bigint generated by default as identity primary key,
  title text not null,
  prize text not null,
  image_url text,
  ends_at timestamp with time zone not null,
  entry_count int default 0,
  status text default 'active', -- active, completed
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for drops
alter table drops enable row level security;

-- Public can view active drops
create policy "Drops are viewable by everyone." on drops
  for select using (true);

-- Only service_role can insert/update drops (for now, or admin if we add roles)
create policy "Admins can insert drops" on drops
    for insert with check (auth.role() = 'service_role');


-- Create entries table
create table entries (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  drop_id bigint references drops(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, drop_id)
);

-- Enable RLS for entries
alter table entries enable row level security;

-- Users can view their own entries
create policy "Users can view own entries." on entries
  for select using (auth.uid() = user_id);

-- Users can insert their own entries
create policy "Users can insert own entries." on entries
  for insert with check (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to automatically create profile on signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Seed some initial data (Optional)
insert into drops (title, prize, image_url, ends_at, entry_count)
values
('Yeezy Boost 350 V2', 'Sneakers', '/drops/yeezy.jpg', now() + interval '2 hours', 1240),
('iPhone 15 Pro Max', 'Tech Bundle', '/drops/iphone.jpg', now() + interval '4 hours', 890),
('$500 Cash Drop', 'Cash', '/drops/cash.jpg', now() + interval '6 hours', 2100);

-- ARCADE & RETENTION SCHEMA

-- Add points and streak tracking to profiles
alter table profiles 
add column if not exists points int default 0,
add column if not exists lifetime_points int default 0,
add column if not exists streak_days int default 0,
add column if not exists last_played_at timestamp with time zone;

-- Create redemptions table
create table redemptions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references profiles(id) not null,
  reward_id text not null,
  cost int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for redemptions
alter table redemptions enable row level security;

-- Users can view their own redemptions
create policy "Users can view own redemptions" on redemptions
  for select using (auth.uid() = user_id);

-- Users can insert their own redemptions (server-side validation required for point deduction)
create policy "Users can insert own redemptions" on redemptions
  for insert with check (auth.uid() = user_id);
